name: Prod Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "app/frontend/**"
      - ".github/workflows/frontend-cicd-prod.yml"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  ROLE_TO_ASSUME: arn:aws:iam::536376965240:role/production-cloud-platform-prod-github-actions-role
  FRONTEND_BUCKET: production-cloud-platform-prod-frontend
  CLOUDFRONT_DISTRIBUTION_ID: E396I4589XOP83

jobs:
  frontend-deploy-prod:
    name: Deploy Frontend to Prod
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}

      - name: Sync frontend to S3
        run: |
          aws s3 sync app/frontend s3://${{ env.FRONTEND_BUCKET }} --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ env.CLOUDFRONT_DISTRIBUTION_ID }}" \
            --paths "/*"